services:
  - type: web
    name: gold-gym-bot
    env: python
    pythonVersion: "3.12"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python xyz_gym.py"
    envVars:
      - key: TELEGRAM_TOKEN
        fromFile: .env
      - key: OPENAI_API_KEY
        fromFile: .env
